# Function: <code>fpu__exception_code</code>

## Status
<b>Regular</b>
<ul>
<li>
<details>
<summary>In <code>4.4.0-21-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579083760,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:469",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579083760,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 104
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>4.8.0-22-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579081536,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:536",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579081536,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 104
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>4.10.0-19-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579079728,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:482",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579079728,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 104
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>4.13.0-16-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579071232,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:475",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579071232,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 102
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>4.15.0-20-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579080096,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:406",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579080096,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 102
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>4.18.0-10-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579085552,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:407",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579085552,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 102
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>5.0.0-13-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579090928,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:405",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579090928,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 102
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>5.3.0-18-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579100400,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:379",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579100400,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 107
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>5.4.0-26-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579102384,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:379",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579102384,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 107
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>5.8.0-25-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579115104,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:402",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579115104,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 107
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>5.11.0-16-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579115120,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:442",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579115120,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 107
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>5.13.0-19-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579121776,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:442",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579121776,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 107
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>5.15.0-25-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579147168,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:454",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579147168,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 107
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>5.19.0-21-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579188256,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:790",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579188256,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 115
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>6.2.0-20-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579244240,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:787",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579244240,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 115
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>6.5.0-9-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579250592,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:787",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579250592,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 115
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>6.8.0-31-generic-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579280016,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:840",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579280016,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 115
    }
  ]
}
```
</details>
</li>
</ul>
<b>Arch</b>
<ul>
<li>
In <code>5.4.0-26-generic-arm64</code>: Absent ❓
</li>
<li>
In <code>5.4.0-26-generic-armhf</code>: Absent ❓
</li>
<li>
In <code>5.4.0-26-generic-ppc64el</code>: Absent ❓
</li>
<li>
In <code>5.4.0-24-generic-riscv64</code>: Absent ❓
</li>
</ul>
<b>Flavor</b>
<ul>
<li>
<details>
<summary>In <code>5.4.0-1009-aws-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579102768,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:379",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579102768,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 107
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>5.4.0-1010-azure-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579035184,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:379",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579035184,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 107
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>5.4.0-1009-gcp-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579102320,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:379",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579102320,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 107
    }
  ]
}
```
</details>
</li>
<li>
<details>
<summary>In <code>5.4.0-26-lowlatency-amd64</code>: ✅</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```

```json
{
  "name": "fpu__exception_code",
  "collision_type": "Unique Global",
  "inline_type": "No",
  "funcs": [
    {
      "addr": 18446744071579107152,
      "name": "fpu__exception_code",
      "external": true,
      "loc": "arch/x86/kernel/fpu/core.c:379",
      "file": "arch/x86/kernel/fpu/core.c",
      "inline": "seen, unknown",
      "caller_inline": [],
      "caller_func": [
        "arch/x86/kernel/traps.c:math_error"
      ]
    }
  ],
  "symbols": [
    {
      "addr": 18446744071579107152,
      "name": "fpu__exception_code",
      "section": ".text",
      "bind": "STB_GLOBAL",
      "size": 107
    }
  ]
}
```
</details>
</li>
</ul>

## Differences
<b>Regular</b>
<ul>
<li>
No changes between <code>4.4.0-21-generic-amd64</code> and <code>4.8.0-22-generic-amd64</code> ✅
</li>
<li>
No changes between <code>4.8.0-22-generic-amd64</code> and <code>4.10.0-19-generic-amd64</code> ✅
</li>
<li>
No changes between <code>4.10.0-19-generic-amd64</code> and <code>4.13.0-16-generic-amd64</code> ✅
</li>
<li>
No changes between <code>4.13.0-16-generic-amd64</code> and <code>4.15.0-20-generic-amd64</code> ✅
</li>
<li>
No changes between <code>4.15.0-20-generic-amd64</code> and <code>4.18.0-10-generic-amd64</code> ✅
</li>
<li>
No changes between <code>4.18.0-10-generic-amd64</code> and <code>5.0.0-13-generic-amd64</code> ✅
</li>
<li>
No changes between <code>5.0.0-13-generic-amd64</code> and <code>5.3.0-18-generic-amd64</code> ✅
</li>
<li>
No changes between <code>5.3.0-18-generic-amd64</code> and <code>5.4.0-26-generic-amd64</code> ✅
</li>
<li>
No changes between <code>5.4.0-26-generic-amd64</code> and <code>5.8.0-25-generic-amd64</code> ✅
</li>
<li>
No changes between <code>5.8.0-25-generic-amd64</code> and <code>5.11.0-16-generic-amd64</code> ✅
</li>
<li>
No changes between <code>5.11.0-16-generic-amd64</code> and <code>5.13.0-19-generic-amd64</code> ✅
</li>
<li>
No changes between <code>5.13.0-19-generic-amd64</code> and <code>5.15.0-25-generic-amd64</code> ✅
</li>
<li>
No changes between <code>5.15.0-25-generic-amd64</code> and <code>5.19.0-21-generic-amd64</code> ✅
</li>
<li>
No changes between <code>5.19.0-21-generic-amd64</code> and <code>6.2.0-20-generic-amd64</code> ✅
</li>
<li>
No changes between <code>6.2.0-20-generic-amd64</code> and <code>6.5.0-9-generic-amd64</code> ✅
</li>
<li>
No changes between <code>6.5.0-9-generic-amd64</code> and <code>6.8.0-31-generic-amd64</code> ✅
</li>
</ul>
<b>Arch</b>
<ul>
<li>
<details>
<summary>Removed between <code>5.4.0-26-generic-amd64</code> and <code>5.4.0-26-generic-arm64</code> ➖</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```
</details>
</li>
<li>
<details>
<summary>Removed between <code>5.4.0-26-generic-amd64</code> and <code>5.4.0-26-generic-armhf</code> ➖</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```
</details>
</li>
<li>
<details>
<summary>Removed between <code>5.4.0-26-generic-amd64</code> and <code>5.4.0-26-generic-ppc64el</code> ➖</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```
</details>
</li>
<li>
<details>
<summary>Removed between <code>5.4.0-26-generic-amd64</code> and <code>5.4.0-24-generic-riscv64</code> ➖</summary>

```c
int fpu__exception_code(struct fpu * fpu, int trap_nr)
```
</details>
</li>
</ul>
<b>Flavor</b>
<ul>
<li>
No changes between <code>5.4.0-26-generic-amd64</code> and <code>5.4.0-1009-aws-amd64</code> ✅
</li>
<li>
No changes between <code>5.4.0-26-generic-amd64</code> and <code>5.4.0-1010-azure-amd64</code> ✅
</li>
<li>
No changes between <code>5.4.0-26-generic-amd64</code> and <code>5.4.0-1009-gcp-amd64</code> ✅
</li>
<li>
No changes between <code>5.4.0-26-generic-amd64</code> and <code>5.4.0-26-lowlatency-amd64</code> ✅
</li>
</ul>
